<?

$keys = 'LHR,CDG,FRA,MAD,AMS,FCO,MUC,BCN,ZRH,DME,CPH,PMI,VIE,OSL,MXP,DUB,ARN,ATH,LIS,HAM,HEL,AGP,PRG,NCE,LPA,WAW,EDI,LED,RHO,BUD,KBP,LCA,OTP,RIX,BOD,PMO,SYD,MEL,BNE,PER,WLG,PTY,SJO,SAL,GUA,MGA,SAP,PUJ,MEX,CUN,GRU,BOG,BSB,EZE,CCS,LIM,REC,GIG,SCL,YYZ,YVR,YUL,YYC,YHZ,YWG,YYT,YXE,HND,PEK,HKG,BKK,SIN,DXB,CAN,CGK,ICN,PVG,KUL,BOM,DEL,MNL,TPE,JED,CTU,KIX,DOH,CJU,SGN,THR,XIY,RUH,CKG,MAA,JNB,CAI,CPT,SSH,HRG,CMN,LOS,NBO,DUR,MIR,ALG,TUN,RAK,ADD,TIP,MRU,ABV,DKR,TNR,AZR,KRT,ATL,ORD,LAX,DFW,DEN,JFK,LAS,IAH,PHX,SFO,CLT,MCO,MIA,MSP,SEA,DTW,PHL,BOS,SLC,HNL,PDX,STL,CVG,MEM,ANC,MLE,SEZ,VVO,IKT,VOG,SVX,UFA,OVB,NSK,TBS';
$data = explode(',',$keys);
$content = file_get_contents('DUB.html');
var_dump($data);
foreach($data as $key=>$one) {
	file_put_contents($one.'.html', $content);
}

?>